// Индекс для поиска по сайту (search.js). Новую страницу добавляй сюда:
// l — язык, t — название, u — путь от корня сайта, g — раздел, k — дополнительные слова для поиска, p — показывать в «Популярном».
window.KONVERTUS_SEARCH = [
  {"l": "ru", "t": "Метры в футы", "u": "converters/meters-feet.html", "g": "Длина", "k": "Километры Метры Дециметры Сантиметры Миллиметры Микрометры Нанометры Мили Морские мили Ярды Футы Дюймы", "p": 1},
  {"l": "ru", "t": "Мили в километры", "u": "converters/miles-km.html", "g": "Длина", "k": "Километры Метры Дециметры Сантиметры Миллиметры Микрометры Нанометры Мили Морские мили Ярды Футы Дюймы"},
  {"l": "ru", "t": "Дюймы в сантиметры", "u": "converters/inches-cm.html", "g": "Длина", "k": "Километры Метры Дециметры Сантиметры Миллиметры Микрометры Нанометры Мили Морские мили Ярды Футы Дюймы"},
  {"l": "ru", "t": "Килограммы в фунты", "u": "converters/kg-pounds.html", "g": "Вес", "k": "Тонны Центнеры Килограммы Граммы Миллиграммы Микрограммы Караты Унции Фунты Стоуны Пуды", "p": 1},
  {"l": "ru", "t": "Граммы в унции", "u": "converters/grams-ounces.html", "g": "Вес", "k": "Тонны Центнеры Килограммы Граммы Миллиграммы Микрограммы Караты Унции Фунты Стоуны Пуды"},
  {"l": "ru", "t": "Цельсий в Фаренгейт", "u": "converters/celsius-fahrenheit.html", "g": "Температура", "k": "Цельсий Фаренгейт Кельвин Ранкин Реомюр градусы погода", "p": 1},
  {"l": "ru", "t": "Цельсий в Кельвин", "u": "converters/celsius-kelvin.html", "g": "Температура", "k": "Цельсий Фаренгейт Кельвин Ранкин Реомюр градусы"},
  {"l": "ru", "t": "Рубли в доллары", "u": "converters/rub-usd.html", "g": "Валюты", "k": "Рубли RUB рубли Доллары США USD доллары Евро EUR евро Юани CNY юани Фунты стерлингов GBP фунты Швейцарские франки CHF франки Иены JPY иены Турецкие лиры TRY лиры Тенге KZT тенге Белорусские рубли BYN белорусские рубли Дирхамы ОАЭ AED дирхамы курс цб валюта обмен", "p": 1},
  {"l": "ru", "t": "Евро в рубли", "u": "converters/eur-rub.html", "g": "Валюты", "k": "Рубли RUB рубли Доллары США USD доллары Евро EUR евро Юани CNY юани Фунты стерлингов GBP фунты Швейцарские франки CHF франки Иены JPY иены Турецкие лиры TRY лиры Тенге KZT тенге Белорусские рубли BYN белорусские рубли Дирхамы ОАЭ AED дирхамы курс цб валюта обмен", "p": 1},
  {"l": "ru", "t": "Мегабайты в гигабайты", "u": "converters/mb-gb.html", "g": "Данные", "k": "Биты Байты Килобайты Мегабайты Гигабайты Терабайты Петабайты Кибибайты Мебибайты Гибибайты Тебибайты Килобиты Мегабиты Гигабиты байты память файл", "p": 1},
  {"l": "ru", "t": "Мегабиты в мегабайты", "u": "converters/mbit-mb.html", "g": "Данные", "k": "Биты Байты Килобайты Мегабайты Гигабайты Терабайты Петабайты Кибибайты Мебибайты Гибибайты Тебибайты Килобиты Мегабиты Гигабиты скорость интернета мбит"},
  {"l": "ru", "t": "Двоичная в десятичную", "u": "converters/bin-dec.html", "g": "Системы счисления", "k": "Двоичная двоичную Восьмеричная восьмеричную Десятичная десятичную Шестнадцатеричная шестнадцатеричную двоичный 0 1 программирование"},
  {"l": "ru", "t": "Десятичная в шестнадцатеричную", "u": "converters/dec-hex.html", "g": "Системы счисления", "k": "Двоичная двоичную Восьмеричная восьмеричную Десятичная десятичную Шестнадцатеричная шестнадцатеричную hex шестнадцатеричный цвет"},
  {"l": "en", "t": "Meters to feet", "u": "en/converters/meters-feet.html", "g": "Length", "k": "Kilometers Meters Decimeters Centimeters Millimeters Micrometers Nanometers Miles Nautical miles Yards Feet Inches", "p": 1},
  {"l": "en", "t": "Miles to kilometers", "u": "en/converters/miles-km.html", "g": "Length", "k": "Kilometers Meters Decimeters Centimeters Millimeters Micrometers Nanometers Miles Nautical miles Yards Feet Inches"},
  {"l": "en", "t": "Inches to centimeters", "u": "en/converters/inches-cm.html", "g": "Length", "k": "Kilometers Meters Decimeters Centimeters Millimeters Micrometers Nanometers Miles Nautical miles Yards Feet Inches"},
  {"l": "en", "t": "Kilograms to pounds", "u": "en/converters/kg-pounds.html", "g": "Weight", "k": "Tonnes Quintals Kilograms Grams Milligrams Micrograms Carats Ounces Pounds Stones Poods", "p": 1},
  {"l": "en", "t": "Grams to ounces", "u": "en/converters/grams-ounces.html", "g": "Weight", "k": "Tonnes Quintals Kilograms Grams Milligrams Micrograms Carats Ounces Pounds Stones Poods"},
  {"l": "en", "t": "Celsius to Fahrenheit", "u": "en/converters/celsius-fahrenheit.html", "g": "Temperature", "k": "Celsius Fahrenheit Kelvin Rankine Réaumur degrees weather", "p": 1},
  {"l": "en", "t": "Celsius to Kelvin", "u": "en/converters/celsius-kelvin.html", "g": "Temperature", "k": "Celsius Fahrenheit Kelvin Rankine Réaumur degrees"},
  {"l": "en", "t": "Rubles to dollars", "u": "en/converters/rub-usd.html", "g": "Currencies", "k": "Rubles RUB rubles US dollars USD dollars Euro EUR euro Yuan CNY yuan Pounds sterling GBP pounds Swiss francs CHF francs Yen JPY yen Turkish lira TRY lira Tenge KZT tenge Belarusian rubles BYN UAE dirhams AED dirhams currency exchange rate money", "p": 1},
  {"l": "en", "t": "Euro to rubles", "u": "en/converters/eur-rub.html", "g": "Currencies", "k": "Rubles RUB rubles US dollars USD dollars Euro EUR euro Yuan CNY yuan Pounds sterling GBP pounds Swiss francs CHF francs Yen JPY yen Turkish lira TRY lira Tenge KZT tenge Belarusian rubles BYN UAE dirhams AED dirhams currency exchange rate money", "p": 1},
  {"l": "en", "t": "Megabytes to gigabytes", "u": "en/converters/mb-gb.html", "g": "Data", "k": "Bits Bytes Kilobytes Megabytes Gigabytes Terabytes Petabytes Kibibytes Mebibytes Gibibytes Tebibytes Kilobits Megabits Gigabits bytes storage file size", "p": 1},
  {"l": "en", "t": "Megabits to megabytes", "u": "en/converters/mbit-mb.html", "g": "Data", "k": "Bits Bytes Kilobytes Megabytes Gigabytes Terabytes Petabytes Kibibytes Mebibytes Gibibytes Tebibytes Kilobits Megabits Gigabits internet speed bandwidth"},
  {"l": "en", "t": "Binary to decimal", "u": "en/converters/bin-dec.html", "g": "Number systems", "k": "Binary binary Octal octal Decimal decimal Hexadecimal hexadecimal binary 0 1 programming"},
  {"l": "en", "t": "Decimal to hexadecimal", "u": "en/converters/dec-hex.html", "g": "Number systems", "k": "Binary binary Octal octal Decimal decimal Hexadecimal hexadecimal hex color programming"},
  {"l": "ru", "t": "Главная", "u": "index.html", "g": "Сайт", "k": "конвертер единиц валют калькулятор"},
  {"l": "ru", "t": "О нас", "u": "about.html", "g": "Сайт", "k": "проект контакты связь почта"},
  {"l": "ru", "t": "Контакты", "u": "about.html#contacts", "g": "Сайт", "k": "связь почта написать"},
  {"l": "en", "t": "Home", "u": "en/index.html", "g": "Site", "k": "unit currency converter calculator"},
  {"l": "en", "t": "About", "u": "en/about.html", "g": "Site", "k": "project contacts contact us email"},
  {"l": "en", "t": "Contacts", "u": "en/about.html#contacts", "g": "Site", "k": "contact us email write"}
];
